apiVersion: v1
kind: Service
metadata:
  name: auto-grand-premium-outlet-service
  namespace: auto-grand-premium-outlet
  labels:
    app: auto-grand-premium-outlet
    service: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: auto-grand-premium-outlet
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: v1
kind: Service
metadata:
  name: auto-grand-premium-outlet-service-nodeport
  namespace: auto-grand-premium-outlet
  labels:
    app: auto-grand-premium-outlet
    service: api-external
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: auto-grand-premium-outlet

