apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-grand-premium-outlet-config
  namespace: auto-grand-premium-outlet
  labels:
    app: auto-grand-premium-outlet
data:
  # Application
  PHX_SERVER: "true"
  PORT: "4000"
  PHX_HOST: "auto-grand-premium-outlet.local"
  MIX_ENV: "prod"
  
  # Database
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "auto_grand_premium_outlet_prod"
  POOL_SIZE: "10"
  
  # Logging
  LOG_LEVEL: "info"

